// Copyright (c) 2026 THONGVAN Alexis
// Licensed under the Good Old Software License v1.0
// See LICENSE file for details

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../check_headers.dart' as check_headers;

/// Fixture-based tests for `tool/check_headers.dart`.
///
/// Each test builds a temporary directory tree, invokes `runCheck` against
/// that tree, and asserts on the return code. We keep assertions on exit
/// codes only (not stderr contents) — exit code is the CI contract, stderr
/// wording can evolve.
const String _validHeader = '''// Copyright (c) 2026 THONGVAN Alexis
// Licensed under the Good Old Software License v1.0
// See LICENSE file for details
''';

void main() {
  group('check_headers.runCheck', () {
    late Directory tempDir;

    setUp(() async {
      tempDir = await Directory.systemTemp.createTemp('check_headers_test_');
    });

    tearDown(() async {
      if (await tempDir.exists()) {
        await tempDir.delete(recursive: true);
      }
    });

    test('returns 0 when every .dart file carries the GOSL header', () async {
      await File(p.join(tempDir.path, 'good.dart')).writeAsString('$_validHeader\nvoid main() {}\n');
      await File(p.join(tempDir.path, 'another_good.dart')).writeAsString('$_validHeader\nclass A {}\n');

      final int code = await check_headers.runCheck(<String>[tempDir.path]);
      expect(code, 0);
    });

    test('returns 1 when at least one .dart file lacks the header', () async {
      await File(p.join(tempDir.path, 'good.dart')).writeAsString('$_validHeader\nvoid main() {}\n');
      await File(p.join(tempDir.path, 'bad.dart')).writeAsString('// TODO: add header\nvoid main() {}\n');

      final int code = await check_headers.runCheck(<String>[tempDir.path]);
      expect(code, 1);
    });

    test('excludes generated files (*.g.dart) from the scan', () async {
      await File(p.join(tempDir.path, 'good.dart')).writeAsString('$_validHeader\nvoid main() {}\n');
      // No header, but the extension is excluded — should still pass.
      await File(p.join(tempDir.path, 'model.g.dart')).writeAsString('// generated by build_runner\nclass ModelImpl {}\n');

      final int code = await check_headers.runCheck(<String>[tempDir.path]);
      expect(code, 0);
    });

    test('tolerates a leading BOM before the header', () async {
      await File(p.join(tempDir.path, 'bom.dart')).writeAsString('﻿$_validHeader\nvoid main() {}\n');

      final int code = await check_headers.runCheck(<String>[tempDir.path]);
      expect(code, 0);
    });

    test('returns 2 when no root exists (misconfiguration)', () async {
      final int code = await check_headers.runCheck(<String>[p.join(tempDir.path, 'nonexistent')]);
      expect(code, 2);
    });
  });
}
